apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "templating-deep-dive.fullname" . }}
  labels:
    {{- include "templating-deep-dive.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ if eq .Values.environment "production" -}} 5 {{ else -}} 2 {{- end }}
  selector:
    matchLabels: {{ include "templating-deep-dive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "templating-deep-dive.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx-service-list
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- if .Values.serviceList | default list | len }}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
          {{- end }}
        - name: nginx-service-dictionary
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- with .Values.securityContext | default dict }}
          # The value of the . after the with block: {{ . }}
          # Release name: {{ $.Release.Name }}
          {{- if and (hasKey . "enabled") .enabled }}
          securityContext:
            runAsUser: {{ .runAsUser }}
            fsGroup: {{ .fsGroup }}
          {{- end }}
          {{- end }}
          {{- if .Values.serviceDictionary | default dict | len }}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
          {{- end }}
