apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "helm-hooks.fullname" . }}-backup-db"
  labels:
    {{- include "helm-hooks.labels" . | nindent 4 }}
  annotations:
    # note: in case post-upgrade fails, it will not rollback the installed release.
    # add --atomic flag in order to rollback
    "helm.sh/hook": post-upgrade # pre-delete,pre-rollback,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation # hook-succeeded
spec:
  backoffLimit: 2 # 10s, 20s, 40s, ...
  template:
    metadata:
      labels:
        {{- include "helm-hooks.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: dummy-backup-db
          image: "alpine:3.20.3"
          command: ["sh", "-c", "echo 'I will fail.'; exit 1;"]
