customName: ''
## @param replicaCount Number of Nginx replicas to deploy
replicaCount: 3
environment: dev
## Settings for NGINX image
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
  name: nginx
  tag: "1.27.0"

containerPorts:
  http: 80
serviceList:
  - type: ClusterIP
    port: 80
  - type: NodePort
    port: 30007
serviceDictionary:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 30007