customName: ''
replicaCount: 3
environment: dev

image:
  name: nginx
  tag: "1.27.0"

securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 2000

containerPorts:
  http: 80
serviceList:
  - type: ClusterIP
    port: 80
  - type: NodePort
    port: 30007
serviceDictionary:
  svc1:
    type: ClusterIP
    port: 80
  svc2:
    type: NodePort
    port: 30007
# to illustrate the $ always refers to the global scope in a nested range.
users:
  - name: Alice
    roles:
      - admin
      - editor
  - name: Bob
    roles:
      - viewer
globalMessage: "Hello from root"
