## @param replicaCount Number of Nginx replicas to deploy
replicaCount: 3
environment: dev
## Settings for NGINX image
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
  name: nginx
  tag: "1.27.0"

## NGINX container ports
##
## @param containerPorts.http
containerPorts:
  http: 80
service:
  enabled: false
  type: ClusterIP
  port: 80