# Not recommended because the secret in *.properties will be packaged in the helm chart.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accessing-files.fullname" . }}
type: Opaque
data:
{{ (.Files.Glob "files/*.properties").AsSecrets | indent 2 }}
